services:
  ros2-bumperbot:
    image: urllib2/rosforge-bumperbot:latest
    ports:
      - "6082:80"
    environment:
      - USER=ubuntu
      - PASSWD=ubuntu
    mem_limit: 10g
    memswap_limit: 8g
    volumes:
      - rosforge_workspace:/home/ubuntu/ros_ws
      - ./continue_config:/home/ubuntu/.continue
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  rosforge_workspace:
